### ISSUE TITLE
ExtRatio flagging private tracker as public. 

### ISSUE THREAD

**Issue by shanethegooner** [Novik/ruTorrent#2390]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Google Chrome 105.0.5195.127
ruTorrent v3.10
‎Debian 9

### Tell us how you installed ruTorrent

Ultra.cc Install Panel.

### Describe the bug

Extratio is applying throttled upload to a private torrent (TVChaosUK) when it should only be flagging public torrents.

### Steps to reproduce

Set 'All torrent's trackers are public' in Extratio.
Add torrent from TVChaosUK.com 

### Expected behavior

Torrent should be added with no upload throttling.
