### ISSUE TITLE
Retracker doesn't to add extra trackers on .meta torrent

### ISSUE THREAD

**Issue by Antorell** [Novik/ruTorrent#2451]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Firefox 110b9
Rutorrent 4.0 
PHP8.1
Ubuntu 22.10

### Tell us how you installed ruTorrent

git clone https://github.com/Novik/ruTorrent.git

Latest commit from the master branch at time or writing.

### Describe the bug

I'm not sure if this is a bug or if it's intended. I couldn't find anything looking here in the past bug reports or on Google. 

I started to notice it a couple of days ago when I disabled udp trackers in rtorrent to try to pin down a crash with rtorrent/libtorrent when some of the Torrent(.meta apparently) pushed by Sonarr to Rtorrent didn't start to download.  

If I add a torrent using a `.meta` link, either from Sonarr or using the add torrent pop-up in Rutorrent, the retracker plugin doesn't edit the torrent to add the extra trackers. 

Regular `.torrent` files aren't affected. 

### Steps to reproduce

Go to any tracker that support .meta and .torrent
Copy the .meta link 
Open the add tracker in Rutorrent
Select folder to save the torrent and paste the .meta link in the add torrent pop-up
Click OK to add the new torrent

### Expected behavior

Assumed to work like when you add a .torrent file. Maybe I'm wrong?

### Additional context

![Capture](https://user-images.githubusercontent.com/25066224/216822091-c9145152-81c8-4158-b48d-8368a3843257.JPG)

**Comment by Antorell** [comment]
So it seems it is as intended. I added a rtorrent script with [d.tracker.inset=](https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html?highlight=d.tracker.insert#term-d-tracker-insert) to inject a public http tracker to all public torrents, and once the .meta torrent is bootsraped rutorrent's retracker injects the other http trackers. 

If anyone ever needs it, here the rtorrent commands to inject a tracker to all public trackers.

```
method.insert= d.addpubtracker, simple|private, "d.tracker.insert=\"32\",\"http://well.knownpublictracker:12345/announce\""

method.set_key=event.download.inserted_new, dl_start_new, "branch=d.is_private=,privatetrackerstuff=,d.addpubtracker="
```

Or if you only need to edit public torrents, use either of these two `event.download.inserted_new` instead :

`method.set_key=event.download.inserted_new, dl_start_new, "branch=d.is_private=,,d.addpubtracker="`

`method.set_key=event.download.inserted_new, dl_start_new, "branch=not=(d.is_private),d.addpubtracker="`
